services:

  yacht:
    image: selfhostedpro/yacht:latest
    container_name: yacht
    restart: unless-stopped
    ports:
      - "8200:8000"
    volumes:
      - yacht:/config
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  yacht:
